const words=[['قطة','🐱'],['كلب','🐶'],['شجرة','🌳'],['سيارة','🚗'],['شمس','☀️'],['سمكة','🐟'],['منزل','🏠'],['طائرة','✈️'],['تفاحة','🍎'],['زهرة','🌸'],['فيل','🐘'],['قلعة','🏰'],['قوس قزح','🌈'],['كتاب','📖'],['كرة','⚽'],['فراشة','🦋'],['سفينة','🚢'],['رائد فضاء','👩‍🚀']];
let state={artist:'',duration:60,round:1,chosen:null,options:[],score:0,time:60,timer:null,drawingData:null};
const $=id=>document.getElementById(id);const screens=['setupScreen','cardsScreen','drawScreen','guessScreen','resultScreen'];function show(id){screens.forEach(x=>$(x).classList.toggle('active',x===id));$('roundLabel').textContent=`الجولة ${state.round}`;window.scrollTo({top:0,behavior:'smooth'})}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function makeCards(){state.options=shuffle(words).slice(0,3);$('cards').innerHTML=state.options.map((w,i)=>`<button class="word-card" data-index="${i}"><span class="word-icon">${w[1]}</span><span>بطاقة ${i+1}</span></button>`).join('');document.querySelectorAll('.word-card').forEach(b=>b.onclick=()=>chooseCard(+b.dataset.index))}
$('startButton').onclick=()=>{state.artist=$('artistName').value.trim()||'الرسّامة';state.duration=+$('duration').value;state.time=state.duration;$('artistGreeting').textContent=`${state.artist}، اختاري بطاقة سرية`;makeCards();show('cardsScreen')};$('newCardsButton').onclick=makeCards;
function chooseCard(i){state.chosen=state.options[i];$('timer').textContent=format(state.duration);show('drawScreen');requestAnimationFrame(()=>{setupCanvas($('drawingCanvas'));startTimer()})}
function format(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function startTimer(){clearInterval(state.timer);state.time=state.duration;state.timer=setInterval(()=>{state.time--; $('timer').textContent=format(state.time);$('timer').classList.toggle('warning',state.time<=10);if(state.time<=0){clearInterval(state.timer);finishDrawing()}},1000)}
const ctxs=new WeakMap();function setupCanvas(canvas){const ratio=Math.max(1,window.devicePixelRatio||1);const rect=canvas.getBoundingClientRect();const cssWidth=Math.max(1,rect.width||canvas.parentElement.clientWidth||600);const cssHeight=Math.max(350,Math.min(600,window.innerHeight*.58));canvas.width=Math.round(cssWidth*ratio);canvas.height=Math.round(cssHeight*ratio);canvas.style.width='100%';canvas.style.height=cssHeight+'px';canvas.style.touchAction='none';const c=canvas.getContext('2d',{desynchronized:true});c.setTransform(ratio,0,0,ratio,0,0);c.fillStyle='#fff';c.fillRect(0,0,cssWidth,cssHeight);ctxs.set(canvas,{c,ratio,down:false,color:'#292d3e',tool:'pen',history:[]});canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture?.(e.pointerId);const p=point(canvas,e);const q=ctxs.get(canvas);q.down=true;q.history.push(c.toDataURL());q.c.beginPath();q.moveX=p.x;q.moveY=p.y;q.c.moveTo(p.x,p.y)};canvas.onpointermove=e=>{e.preventDefault();const q=ctxs.get(canvas);if(!q||!q.down)return;const p=point(canvas,e);q.c.strokeStyle=q.tool==='eraser'?'#fff':q.color;q.c.lineWidth=q.tool==='eraser'?28:5;q.c.lineCap='round';q.c.lineJoin='round';q.c.lineTo(p.x,p.y);q.c.stroke();q.c.beginPath();q.c.moveTo(p.x,p.y)};canvas.onpointerup=canvas.onpointercancel=canvas.onpointerleave=e=>{const q=ctxs.get(canvas);if(q)q.down=false}}
function point(canvas,e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function finishDrawing(){clearInterval(state.timer);state.drawingData=$('drawingCanvas').toDataURL();$('guessArtist').textContent=state.artist;const gc=$('guessCanvas');const img=new Image();img.onload=()=>{gc.width=$('drawingCanvas').width;gc.height=$('drawingCanvas').height;gc.getContext('2d').drawImage(img,0,0,gc.width,gc.height)};img.src=state.drawingData;const opts=shuffle([state.chosen,...shuffle(words.filter(w=>w[0]!==state.chosen[0])).slice(0,3)]);$('guessOptions').innerHTML=opts.map(w=>`<button class="guess-option" data-answer="${w[0]}">${w[1]} ${w[0]}</button>`).join('');document.querySelectorAll('.guess-option').forEach(b=>b.onclick=()=>submitGuess(b.dataset.answer));$('guessMessage').textContent='';show('guessScreen')}
$('finishDrawing').onclick=finishDrawing;document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{const q=ctxs.get($('drawingCanvas'));if(!q)return;if(b.dataset.tool){q.tool=b.dataset.tool;document.querySelectorAll('.tool[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}if(b.id==='clearButton'){q.c.save();q.c.setTransform(1,0,0,1,0,0);q.c.fillStyle='#fff';q.c.fillRect(0,0,$('drawingCanvas').width,$('drawingCanvas').height);q.c.restore()}if(b.id==='undoButton'){const src=q.history.pop();if(src){const im=new Image();im.onload=()=>q.c.drawImage(im,0,0,$('drawingCanvas').width/q.ratio,$('drawingCanvas').height/q.ratio);im.src=src}}});document.querySelectorAll('.color').forEach(b=>b.onclick=()=>{const q=ctxs.get($('drawingCanvas'));if(!q)return;q.color=b.dataset.color;q.tool='pen';document.querySelectorAll('.color').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.querySelectorAll('.tool[data-tool]').forEach(x=>x.classList.toggle('active',x.dataset.tool==='pen'))});
function submitGuess(answer){if(answer===state.chosen[0]){state.score++;$('resultTitle').textContent='إجابة صحيحة! 🎉';$('resultText').textContent='حصلتم على نقطة، أحسنتم يا أصدقاء!'}else{$('resultTitle').textContent='محاولة رائعة! 🌟';$('resultText').textContent='لا بأس، استمروا في المحاولة في الجولة القادمة.'}$('answer').textContent=state.chosen[0];show('resultScreen')}$('submitCustom').onclick=()=>{const v=$('customGuess').value.trim();if(v)submitGuess(v)};$('nextRound').onclick=()=>{state.round++;makeCards();show('cardsScreen')};$('restart').onclick=()=>{state={...state,round:1,score:0};show('setupScreen')};
